/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranscodingRouteImport } from './routes/transcoding'
import { Route as ResolutionsRouteImport } from './routes/resolutions'
import { Route as NotificationRouteImport } from './routes/notification'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiGatewayRouteImport } from './routes/api-gateway'
import { Route as AdboxBackendRouteImport } from './routes/adbox-backend'
import { Route as IndexRouteImport } from './routes/index'

const TranscodingRoute = TranscodingRouteImport.update({
  id: '/transcoding',
  path: '/transcoding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolutionsRoute = ResolutionsRouteImport.update({
  id: '/resolutions',
  path: '/resolutions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationRoute = NotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayRoute = ApiGatewayRouteImport.update({
  id: '/api-gateway',
  path: '/api-gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const AdboxBackendRoute = AdboxBackendRouteImport.update({
  id: '/adbox-backend',
  path: '/adbox-backend',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adbox-backend': typeof AdboxBackendRoute
  '/api-gateway': typeof ApiGatewayRoute
  '/login': typeof LoginRoute
  '/notification': typeof NotificationRoute
  '/resolutions': typeof ResolutionsRoute
  '/transcoding': typeof TranscodingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adbox-backend': typeof AdboxBackendRoute
  '/api-gateway': typeof ApiGatewayRoute
  '/login': typeof LoginRoute
  '/notification': typeof NotificationRoute
  '/resolutions': typeof ResolutionsRoute
  '/transcoding': typeof TranscodingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adbox-backend': typeof AdboxBackendRoute
  '/api-gateway': typeof ApiGatewayRoute
  '/login': typeof LoginRoute
  '/notification': typeof NotificationRoute
  '/resolutions': typeof ResolutionsRoute
  '/transcoding': typeof TranscodingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adbox-backend'
    | '/api-gateway'
    | '/login'
    | '/notification'
    | '/resolutions'
    | '/transcoding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adbox-backend'
    | '/api-gateway'
    | '/login'
    | '/notification'
    | '/resolutions'
    | '/transcoding'
  id:
    | '__root__'
    | '/'
    | '/adbox-backend'
    | '/api-gateway'
    | '/login'
    | '/notification'
    | '/resolutions'
    | '/transcoding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdboxBackendRoute: typeof AdboxBackendRoute
  ApiGatewayRoute: typeof ApiGatewayRoute
  LoginRoute: typeof LoginRoute
  NotificationRoute: typeof NotificationRoute
  ResolutionsRoute: typeof ResolutionsRoute
  TranscodingRoute: typeof TranscodingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transcoding': {
      id: '/transcoding'
      path: '/transcoding'
      fullPath: '/transcoding'
      preLoaderRoute: typeof TranscodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolutions': {
      id: '/resolutions'
      path: '/resolutions'
      fullPath: '/resolutions'
      preLoaderRoute: typeof ResolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification': {
      id: '/notification'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof NotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-gateway': {
      id: '/api-gateway'
      path: '/api-gateway'
      fullPath: '/api-gateway'
      preLoaderRoute: typeof ApiGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adbox-backend': {
      id: '/adbox-backend'
      path: '/adbox-backend'
      fullPath: '/adbox-backend'
      preLoaderRoute: typeof AdboxBackendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdboxBackendRoute: AdboxBackendRoute,
  ApiGatewayRoute: ApiGatewayRoute,
  LoginRoute: LoginRoute,
  NotificationRoute: NotificationRoute,
  ResolutionsRoute: ResolutionsRoute,
  TranscodingRoute: TranscodingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
